name: image_cropperapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker:
  image_cropper:
  animated_splash_screen: ^1.3.0
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/EyeDoc.png"

flutter:
  uses-material-design: true
  assets:
    - assets/eyedoclogo.png
    - assets/img_splash.png